### ISSUE TITLE
Feature Request: RTC Support

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/Apple-II_MiSTer#11]
Would it be possible to add RTC support to the core?  It seems none of the three Apple cores have it.

Here is an article about the various types of RTC support for the Apple II:
https://en.wikipedia.org/wiki/Apple_II_system_clocks

**Comment by Newsdee** [comment]
This was solved already:  https://github.com/MiSTer-devel/Apple-II_MiSTer/commit/b7155175a6fa058dc6778092ae0be15f2fcbf8e3

**Comment by ajgowans** [comment]
Can I close this @alanswx ?

**Comment by Newsdee** [comment]
I can confirm the Apple II clock is automatically setup to the MiSTer clock when running Apple II Desktop

**Comment by alanswx** [comment]
It should be closed.
