### ISSUE TITLE
Add write protect for disk

### ISSUE THREAD

**Issue by centercirclesolutions** [MiSTer-devel/Apple-II_MiSTer#19]
Would it be easy to add an option to write protect disk 1. Some games require the write protect to be on in order to work. If there is another work around for this let me know... I've tried many things and looked around to see if there was any other solution.

**Comment by sorgelig** [comment]
You may set file read-only. It should become a write protected disk.

**Comment by centercirclesolutions** [comment]
I tried setting the Readonly for both the disk files (.nib / .dsk) and it still hangs ( Wizardry I ) so it must be something else going on. Thanks for the reply I'll try some other things to see if I can figure out what is causing it to stop after the initial screen
