### ISSUE TITLE
Release build?

### ISSUE THREAD

**Issue by Newsdee** [MiSTer-devel/Apple-II_MiSTer#32]
I'd like to release the current version of the Apple2 core, as I don't plan to add anything in the near future.
Shall I send a PR with only the compiled binary?  Or is there a different way to package a release?

**Comment by sorgelig** [comment]
I plan to make release for several core in couple days

**Comment by wwark** [comment]
Hi,
Yesterday the rbf of apple ii seems not pushed of GitHub page.

**Comment by Newsdee** [comment]
I closed it due to the news - but then noticed the rbf was not pushed on github (as vwark pointed out)

**Comment by sorgelig** [comment]
Sorry for that.
Pushed rbf.
