### ISSUE TITLE
Joystick up and down missing

### ISSUE THREAD

**Issue by bonnefoi** [MiSTer-devel/Apple-II_MiSTer#4]
Up and down are no more...

I could swap with the OSD option "Analog X/Y" but it's left/right or up/down exclusively.

**Comment by pashdown** [comment]
I came here to post this ^.

**Comment by bonnefoi** [comment]
yes, Boulder Dash is seriously difficult when you start with a boulder on the right and on the left :)

**Comment by ulao** [comment]
right, spent hours trying to find a way to make my controller work... what gives? Kinda need 4 directions to use a joystick, is this a noted bug or a planned/not planned  feaure

**Comment by sorgelig** [comment]
All bug reports are noted. But this is NOT forum. So don't expect replies. It will be fixed when it will be fixed.

**Comment by jbarros35** [comment]
my keyboard is not recognised, even tough I can select the core and map all buttons

**Comment by shertz43** [comment]
You need to use an analog joystick for the Apple ][ to work.

**Comment by pashdown** [comment]
Left/right works with a digital joystick, up/down does not.  If analog was required, left/right wouldn't work either.

**Comment by steven-a-wilson** [comment]
I haven't tracked down the actual bug, but from what I've seen so far I suspect the particular issue is reading more than one paddle/axis with a single access to the PTRIG address ($C070). Programs that use the "supported" method of calling the PREAD ($FB1E) subroutine for each axis seemingly don't run into this problem. For example, here's a BASIC program that seems to report reasonable values for the X and Y axes (or paddles 0 and 1):

```
10 PRINT PDL(0)" "PDL(1)
20 GOTO 10
```

**Comment by steven-a-wilson** [comment]
Actually, the more I look at this, the more I think it's somehow a configuration/mapping issue. There are definitely some problems with how certain games interpret the joystick position, but I haven't seen any problems with up and down being totally absent. The game I thought I saw this with (Phantoms Five) simply doesn't allow the player to move vertically. The only game anyone else has mentioned is Boulder Dash, which works fine for me with the analog stick. The other problems I've seen are related to the overall range/centering of the stick, which was apparently also an issue with some games and joysticks on original hardware.

**Comment by pashdown** [comment]
Try Drol.

**Comment by steven-a-wilson** [comment]
Drol seems fine on my setup. I'm pretty sure the underlying core's basic joystick function is reasonable with a properly mapped analog stick, and either something is going wrong with people mapping the stick or something is going wrong with the way D-pad inputs are handled in the top-level HDL.

**Comment by pashdown** [comment]
I haven't tried the A2 with analog stick, but I do know that left-right works fine with a d-pad, up-down does not.  If the mapping was wrong, wouldn't that affect everything on MiSTer?

**Comment by steven-a-wilson** [comment]
This seems to depend on the connected controller. I do see this issue trying to use the d-pad on a digital-only controller (Saturn controller via an adapter). But on modern dual-stick pads (e.g. DualShock 3, Logitech F310), the analog stick works as expected while the d-pad does nothing. I think this might be an issue in Main, because it looks like the core itself doesn't actually use the d-pad inputs.

**Comment by steven-a-wilson** [comment]
I believe this is fixed with the current core+Main. It might be necessary to map the controller again for the fix to take effect.

**Comment by sorgelig** [comment]
yeah, it should be fixed.
