### ISSUE TITLE
Feature request: add spinner/paddle support

### ISSUE THREAD

**Issue by Newsdee** [MiSTer-devel/Apple-II_MiSTer#8]
Many Apple II games use paddles and would work great with a spinner.
Would it be possible to add spinner/paddle support?

**Comment by sorgelig** [comment]
should be possible. I will check.

**Comment by Newsdee** [comment]
Thank you! Early games like Dogfight, Star Blaster, or Sabotage really benefit from it

**Comment by Newsdee** [comment]
This is included in the latest official release. Thank you so much for adding it, @steven-a-wilson !
